# Dicionário com todos os textos da aplicação em diferentes idiomas
LANGUAGES = {
    'pt': {
        'welcome': "Bem-vindo ao Gerenciador de Tarefas Sprintboard!",
        'menu_title': "--- Gerenciador de Tarefas Sprintboard ---",
        'add_task': "1. Adicionar uma nova tarefa",
        'list_pending': "2. Listar tarefas pendentes",
        'list_all': "3. Listar tarefas por status",
        'mark_completed': "4. Marcar uma tarefa como concluída",
        'cancel_task': "5. Cancelar uma tarefa",
        'remove_task': "6. Remover uma tarefa",
        'exit': "7. Sair",
        'enter_choice': "Digite sua escolha: ",
        'task_description': "Digite a descrição da tarefa: ",
        'due_date': "Digite a data de vencimento (AAAA-MM-DD HH:MM) [opcional]: ",
        'urgency': "Digite a urgência (Alta, Normal, Baixa) [opcional, padrão: Normal]: ",
        'invalid_date': "Formato de data inválido. A tarefa será adicionada sem data de vencimento.",
        'task_added': "Tarefa adicionada com sucesso!",
        'no_tasks_found': "Nenhuma tarefa pendente encontrada.",
        'list_status_choice': "Selecione o status para listar (Pending, Completed, Canceled, All): ",
        'no_tasks_status': "Nenhuma tarefa encontrada com este status.",
        'task_list_header': "ID: {id} | Descrição: {description} | Status: {status} | Criado em: {creation_date}",
        'task_details': "Data de Vencimento: {due_date} | Urgência: {urgency}",
        'enter_id_completed': "Digite o ID da tarefa para marcar como concluída: ",
        'enter_id_canceled': "Digite o ID da tarefa para cancelar: ",
        'enter_id_removed': "Digite o ID da tarefa para remover: ",
        'invalid_input_number': "Entrada inválida. Por favor, digite um número.",
        'exiting': "Saindo do Sprintboard. Adeus!",
        'invalid_choice': "Escolha inválida. Por favor, tente novamente."
    },
    'en': {
        'welcome': "Welcome to the Sprintboard Task Manager!",
        'menu_title': "--- Sprintboard Task Manager ---",
        'add_task': "1. Add a new task",
        'list_pending': "2. List pending tasks",
        'list_all': "3. List tasks by status",
        'mark_completed': "4. Mark a task as completed",
        'cancel_task': "5. Cancel a task",
        'remove_task': "6. Remove a task",
        'exit': "7. Exit",
        'enter_choice': "Enter your choice: ",
        'task_description': "Enter task description: ",
        'due_date': "Enter due date (YYYY-MM-DD HH:MM) [optional]: ",
        'urgency': "Enter urgency (High, Normal, Low) [optional, default: Normal]: ",
        'invalid_date': "Invalid date format. Task will be added without a due date.",
        'task_added': "Task added successfully!",
        'no_tasks_found': "No pending tasks found.",
        'list_status_choice': "Select status to list (Pending, Completed, Canceled, All): ",
        'no_tasks_status': "No tasks found with this status.",
        'task_list_header': "ID: {id} | Description: {description} | Status: {status} | Created: {creation_date}",
        'task_details': "Due Date: {due_date} | Urgency: {urgency}",
        'enter_id_completed': "Enter the ID of the task to mark as completed: ",
        'enter_id_canceled': "Enter the ID of the task to cancel: ",
        'enter_id_removed': "Enter the ID of the task to remove: ",
        'invalid_input_number': "Invalid input. Please enter a number.",
        'exiting': "Exiting Sprintboard. Goodbye!",
        'invalid_choice': "Invalid choice. Please try again."
    }
}